# Generated by Django 3.1.7 on 2021-03-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V_Maven', '0003_auto_20210311_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
